# Use custom format
# format = """
# [┌───────────────────>](bold green)
# [│](bold green)$directory$rust$package
# [└─>](bold green) """
format = """$all"""

# Wait 10 milliseconds for starship to check files under the current directory.
scan_timeout = 3000

# Disable the blank line at the start of the prompt
add_newline = false

# Set "foo" as custom color palette
# palette = "foo"

# Define custom colors
# [palettes.foo]
# Overwrite existing color
# blue = "21"
# Define new color
# mustard = "#af8700"

continuation_prompt = "▶▶"

[git_commit]
style = "bold white"

[character]
success_symbol = ""
error_symbol = ""

[aws]
symbol = "  "

[buf]
symbol = " "

[c]
symbol = " "

[conda]
symbol = " "

[dart]
symbol = " "

[directory]
read_only = " "
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style) "

[docker_context]
symbol = " "

[elixir]
symbol = " "

[elm]
symbol = " "

[git_branch]
symbol = " "

[golang]
symbol = " "

[haskell]
symbol = " "

[hg_branch]
symbol = " "

[java]
symbol = " "

[julia]
symbol = " "

[lua]
symbol = " "

[memory_usage]
symbol = " "

[meson]
symbol = "喝 "

[nim]
symbol = " "

[nix_shell]
symbol = " "

[nodejs]
symbol = " "

[package]
symbol = " "

[python]
symbol = " "

[rlang]
symbol = "ﳒ "

[ruby]
symbol = " "

[rust]
symbol = " "

[scala]
symbol = " "

[spack]
symbol = "🅢 "

